"""
template_manager — 模板管理插件
═══════════════════════════════════
管理代码模板，在编码前注入匹配的模板骨架。
"""

import os
import json
from pathlib import Path


_TEMPLATES = {
    "flask_app": {
        "python": '''#!/usr/bin/env python3
"""Flask Application — Generated by cx2118 Script Weaver"""

from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route("/api/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"})


if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)
''',
        "description": "Flask Web 应用模板",
    },
    "fastapi_app": {
        "python": '''#!/usr/bin/env python3
"""FastAPI Application — Generated by cx2118 Script Weaver"""

from fastapi import FastAPI

app = FastAPI(title="My API")


@app.get("/api/health")
async def health():
    return {"status": "ok"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
''',
        "description": "FastAPI Web 应用模板",
    },
    "cli_tool": {
        "python": '''#!/usr/bin/env python3
"""CLI Tool — Generated by cx2118 Script Weaver"""

import argparse


def main():
    parser = argparse.ArgumentParser(description="CLI Tool")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    args = parser.parse_args()
    # Your logic here
    print("Hello from CLI Tool!")


if __name__ == "__main__":
    main()
''',
        "description": "命令行工具模板",
    },
}


def on_load(config=None, engine=None):
    return config


async def on_hook(context=None, config=None, **kwargs):
    """Hook handler for template injection."""
    if not context or not context.data:
        return None
    if config is None:
        config = {}
    if not config.get("auto_inject_templates", False):
        return None

    hook_point = context.hook_point if context else ""
    requirements = context.data.get("requirements", "") if context else ""

    if hook_point == "before_director_plan" and requirements:
        matched = _match_template(requirements)
        if matched:
            context.set_data("suggested_template", matched)
            context.set_data("template_code", _TEMPLATES[matched].get("python", ""))

    return {"data": context.data}


def list_templates() -> list:
    """List available templates."""
    return [
        {"name": name, "description": info["description"]}
        for name, info in _TEMPLATES.items()
    ]


def get_template(name: str) -> dict:
    """Get a template by name."""
    return _TEMPLATES.get(name, {})


def _match_template(requirements: str) -> str:
    """Simple keyword matching to suggest a template."""
    rl = requirements.lower()
    if "fastapi" in rl:
        return "fastapi_app"
    if "flask" in rl:
        return "flask_app"
    if "cli" in rl or "命令行" in rl or "command line" in rl:
        return "cli_tool"
    return ""
